# Generated by Django 4.0.4 on 2022-05-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_items_bidder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
