# Generated by Django 4.0.4 on 2022-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_item_description_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
