# Generated by Django 4.0.4 on 2022-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bidder_items_remove_bidder_name_bidder_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
