# Generated by Django 4.0.4 on 2022-06-01 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_item_watchlist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='item',
        ),
        migrations.AddField(
            model_name='bidder',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.item'),
            preserve_default=False,
        ),
    ]
