# Generated by Django 4.0.4 on 2022-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_bidder_item_bidder_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='bidder',
        ),
        migrations.AddField(
            model_name='bidder',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
